name: Build and upload

on:
  release:
    types:
      - created

env:
  BINARY_NAME: 'http-trace'

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [darwin, linux]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.6'

    - name: Build
      run: GOOS=${{ matrix.os }} GOARCH=amd64 go build -o ./bin/${{ env.BINARY_NAME }}-${{ matrix.os }}

    - name: Upload
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./bin/${{ env.BINARY_NAME }}-${{ matrix.os }}
        asset_name: ${{ env.BINARY_NAME }}-${{ matrix.os }}
        asset_content_type: binary/octet-stream
