name: Tests, formatting and vet

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run-tests-fmt-vet:
    name: Run tests, formatting and vet
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.6'

    - name: Run Tests
      run: go test ./...

    - name: Formatting
      run: gofmt -s -w . && git diff --exit-code

    - name: Go vet
      run: go vet ./...
